# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Gian Reggianis Portfolio
# Description of the Site
description: My personal portfolio
# URL of Image of the Site
site-image: /gian-reggiani.github.io/assets/images/IK5A7486_JPG.jpg
# Keywords of the Site
site-keywords: Portfolio, resume, blog
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: gian.reggiani@hotmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: /
github_username:  gian-reggiani
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Gian Reggiani
# URL for the Image of the Author
author-image: /gian-reggiani.github.io/assets/images/IK5A7486_JPG.jpg
# 60 Words About the Author
author-about: I am an enthusiastic, self-motivated and self-confident person. I enjoy working by myself and as a part of a team, as I have experienced during the years
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://gian-reggiani.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
